// frontend/src/services/demoData.service.ts

export const demoDataService = {
    // ==================== AWS DEMO DATA ====================
    
    getAWSCostAnalytics: (accountId: string) => ({
      currentMonth: {
        total: 12450.50,
        breakdown: [
          { service: 'EC2', cost: 4200.00, percentage: 33.7, trend: '+5%' },
          { service: 'RDS', cost: 2800.00, percentage: 22.5, trend: '+12%' },
          { service: 'S3', cost: 1850.00, percentage: 14.9, trend: '-3%' },
          { service: 'Lambda', cost: 980.00, percentage: 7.9, trend: '+8%' },
          { service: 'CloudFront', cost: 720.00, percentage: 5.8, trend: '+2%' },
          { service: 'ELB', cost: 650.00, percentage: 5.2, trend: '+4%' },
          { service: 'Others', cost: 1250.50, percentage: 10.0, trend: '+1%' },
        ],
        trend: [
          { month: 'Jan', cost: 11200 },
          { month: 'Feb', cost: 11800 },
          { month: 'Mar', cost: 12450.50 },
        ],
      },
      lastMonth: 11800.00,
      forecast: 13100.00,
      savingsOpportunity: 2340.00,
    }),
  
    getAWSOptimizations: (accountId: string) => [
      {
        id: 'opt-1',
        type: 'Rightsizing',
        title: 'Rightsize overprovisioned EC2 instances',
        description: '15 EC2 instances are running with less than 20% CPU utilization',
        currentCost: 840.00,
        potentialSavings: 420.00,
        savingsPercent: 50,
        priority: 'High',
        effort: 'Low',
        resources: ['i-1234abcd', 'i-5678efgh', 'i-9012ijkl'],
      },
      {
        id: 'opt-2',
        type: 'Reserved Instances',
        title: 'Purchase Reserved Instances for steady workloads',
        description: 'Save up to 72% on long-running instances',
        currentCost: 2400.00,
        potentialSavings: 1200.00,
        savingsPercent: 50,
        priority: 'High',
        effort: 'Low',
        resources: [],
      },
      {
        id: 'opt-3',
        type: 'Storage',
        title: 'Delete old EBS snapshots',
        description: '127 snapshots older than 90 days',
        currentCost: 180.00,
        potentialSavings: 180.00,
        savingsPercent: 100,
        priority: 'Medium',
        effort: 'Low',
        resources: [],
      },
      {
        id: 'opt-4',
        type: 'Idle Resources',
        title: 'Stop idle RDS instances',
        description: '3 RDS instances with no connections in last 7 days',
        currentCost: 560.00,
        potentialSavings: 420.00,
        savingsPercent: 75,
        priority: 'Medium',
        effort: 'Medium',
        resources: ['db-prod-replica-old', 'db-staging-unused', 'db-test-archived'],
      },
      {
        id: 'opt-5',
        type: 'Auto-Scaling',
        title: 'Enable auto-scaling for variable workloads',
        description: 'Configure auto-scaling groups for non-production environments',
        currentCost: 340.00,
        potentialSavings: 120.00,
        savingsPercent: 35,
        priority: 'Low',
        effort: 'Medium',
        resources: [],
      },
    ],
  
    getAWSSecurity: (accountId: string) => ({
      score: 78,
      trend: '+5',
      issues: {
        critical: 3,
        high: 12,
        medium: 28,
        low: 45,
      },
      findings: [
        {
          id: 'sec-1',
          severity: 'Critical',
          title: 'S3 bucket publicly accessible',
          description: 'Bucket "prod-data-backups" has public read access',
          resource: 'arn:aws:s3:::prod-data-backups',
          remediation: 'Remove public access and enable bucket encryption',
          compliance: ['PCI-DSS', 'HIPAA'],
        },
        {
          id: 'sec-2',
          severity: 'Critical',
          title: 'Root account MFA not enabled',
          description: 'AWS root account does not have MFA enabled',
          resource: 'AWS Account',
          remediation: 'Enable MFA for root account immediately',
          compliance: ['CIS AWS Foundations'],
        },
        {
          id: 'sec-3',
          severity: 'High',
          title: 'Security group allows unrestricted access',
          description: 'Security group sg-1234abcd allows 0.0.0.0/0 on port 22',
          resource: 'sg-1234abcd',
          remediation: 'Restrict SSH access to specific IP ranges',
          compliance: ['CIS AWS Foundations'],
        },
        {
          id: 'sec-4',
          severity: 'High',
          title: 'IAM user with admin access key older than 90 days',
          description: 'Access keys should be rotated regularly',
          resource: 'iam-user-john-doe',
          remediation: 'Rotate access keys and implement key rotation policy',
          compliance: ['CIS AWS Foundations', 'SOC 2'],
        },
        {
          id: 'sec-5',
          severity: 'Medium',
          title: 'CloudTrail not enabled in all regions',
          description: 'CloudTrail logging is only enabled in us-east-1',
          resource: 'CloudTrail',
          remediation: 'Enable CloudTrail in all active regions',
          compliance: ['PCI-DSS', 'HIPAA'],
        },
      ],
    }),
  
    getAWSResources: (accountId: string) => [
      {
        id: 'i-1234abcd',
        name: 'web-server-01',
        type: 'EC2 Instance',
        region: 'us-east-1',
        state: 'running',
        instanceType: 't3.large',
        vpc: 'vpc-prod-01',
        launched: '2026-01-15T10:30:00Z',
        monthlyCost: 65.00,
        tags: { Environment: 'Production', Team: 'Platform' },
      },
      {
        id: 'i-5678efgh',
        name: 'app-server-01',
        type: 'EC2 Instance',
        region: 'us-east-1',
        state: 'running',
        instanceType: 'm5.xlarge',
        vpc: 'vpc-prod-01',
        launched: '2026-02-01T14:20:00Z',
        monthlyCost: 140.00,
        tags: { Environment: 'Production', Team: 'Backend' },
      },
      {
        id: 'i-9012ijkl',
        name: 'web-server-02',
        type: 'EC2 Instance',
        region: 'us-east-1',
        state: 'stopped',
        instanceType: 't3.large',
        vpc: 'vpc-prod-01',
        launched: '2026-01-20T09:15:00Z',
        monthlyCost: 65.00,
        tags: { Environment: 'Production', Team: 'Platform' },
      },
      {
        id: 'i-3456mnop',
        name: 'test-instance-01',
        type: 'EC2 Instance',
        region: 'us-west-2',
        state: 'running',
        instanceType: 't3.medium',
        vpc: 'vpc-dev-01',
        launched: '2026-02-15T11:00:00Z',
        monthlyCost: 30.00,
        tags: { Environment: 'Development', Team: 'QA' },
      },
      {
        id: 'vol-1234abcd',
        name: 'data-volume-01',
        type: 'EBS Volume',
        region: 'us-east-1',
        state: 'in-use',
        size: '500 GB',
        volumeType: 'gp3',
        attachedTo: 'i-1234abcd',
        monthlyCost: 40.00,
        tags: { Environment: 'Production' },
      },
      {
        id: 'vol-5678efgh',
        name: 'backup-volume-01',
        type: 'EBS Volume',
        region: 'us-east-1',
        state: 'available',
        size: '1000 GB',
        volumeType: 'gp3',
        attachedTo: null,
        monthlyCost: 80.00,
        tags: { Environment: 'Production' },
      },
      {
        id: 'snap-1234abcd',
        name: 'weekly-backup-20260301',
        type: 'EBS Snapshot',
        region: 'us-east-1',
        state: 'available',
        size: '500 GB',
        monthlyCost: 25.00,
        tags: { BackupType: 'Weekly' },
      },
      {
        id: 'lb-1234abcd',
        name: 'prod-alb-main',
        type: 'Application Load Balancer',
        region: 'us-east-1',
        state: 'running',
        vpc: 'vpc-prod-01',
        monthlyCost: 45.00,
        tags: { Environment: 'Production' },
      },
    ],
  
    getAWSRDSDatabases: (accountId: string) => [
      {
        id: 'db-1',
        name: 'prod-mysql-db',
        engine: 'MySQL 8.0',
        instanceClass: 'db.r5.large',
        status: 'available',
        region: 'us-east-1',
        multiAZ: true,
        storage: '100 GB',
        backup: 'Enabled (7 days)',
        monthlyCost: 280.00,
        connections: 45,
        cpu: 35,
        memory: 62,
      },
      {
        id: 'db-2',
        name: 'analytics-postgres',
        engine: 'PostgreSQL 14',
        instanceClass: 'db.m5.xlarge',
        status: 'available',
        region: 'us-east-1',
        multiAZ: false,
        storage: '250 GB',
        backup: 'Enabled (14 days)',
        monthlyCost: 420.00,
        connections: 12,
        cpu: 18,
        memory: 45,
      },
      {
        id: 'db-3',
        name: 'staging-mysql-db',
        engine: 'MySQL 8.0',
        instanceClass: 'db.t3.medium',
        status: 'available',
        region: 'us-west-2',
        multiAZ: false,
        storage: '50 GB',
        backup: 'Enabled (3 days)',
        monthlyCost: 85.00,
        connections: 8,
        cpu: 25,
        memory: 38,
      },
      {
        id: 'db-4',
        name: 'dev-postgres-db',
        engine: 'PostgreSQL 15',
        instanceClass: 'db.t3.small',
        status: 'stopped',
        region: 'us-east-1',
        multiAZ: false,
        storage: '20 GB',
        backup: 'Enabled (1 day)',
        monthlyCost: 35.00,
        connections: 0,
        cpu: 0,
        memory: 0,
      },
      {
        id: 'db-5',
        name: 'reporting-aurora',
        engine: 'Aurora MySQL',
        instanceClass: 'db.r5.2xlarge',
        status: 'available',
        region: 'us-east-1',
        multiAZ: true,
        storage: '500 GB',
        backup: 'Enabled (30 days)',
        monthlyCost: 850.00,
        connections: 120,
        cpu: 65,
        memory: 78,
      },
    ],
  
    // ==================== AZURE DEMO DATA ====================
    
    getAzureCostAnalytics: (accountId: string) => ({
      currentMonth: {
        total: 15680.75,
        breakdown: [
          { service: 'Virtual Machines', cost: 5200.00, percentage: 33.2, trend: '+7%' },
          { service: 'Azure SQL', cost: 3400.00, percentage: 21.7, trend: '+10%' },
          { service: 'Storage Accounts', cost: 2100.00, percentage: 13.4, trend: '-2%' },
          { service: 'App Services', cost: 1850.00, percentage: 11.8, trend: '+15%' },
          { service: 'Azure Functions', cost: 980.00, percentage: 6.2, trend: '+5%' },
          { service: 'Load Balancer', cost: 720.00, percentage: 4.6, trend: '+3%' },
          { service: 'Others', cost: 1430.75, percentage: 9.1, trend: '+2%' },
        ],
        trend: [
          { month: 'Jan', cost: 14200 },
          { month: 'Feb', cost: 14900 },
          { month: 'Mar', cost: 15680.75 },
        ],
      },
      lastMonth: 14900.00,
      forecast: 16500.00,
      savingsOpportunity: 2850.00,
    }),
  
    // ==================== GCP DEMO DATA ====================
    
    getGCPCostAnalytics: (accountId: string) => ({
      currentMonth: {
        total: 13240.50,
        breakdown: [
          { service: 'Compute Engine', cost: 4500.00, percentage: 34.0, trend: '+6%' },
          { service: 'Cloud SQL', cost: 2800.00, percentage: 21.1, trend: '+8%' },
          { service: 'Cloud Storage', cost: 1900.00, percentage: 14.3, trend: '-1%' },
          { service: 'Cloud Functions', cost: 1200.00, percentage: 9.1, trend: '+12%' },
          { service: 'GKE', cost: 1500.00, percentage: 11.3, trend: '+5%' },
          { service: 'Others', cost: 1340.50, percentage: 10.2, trend: '+3%' },
        ],
        trend: [
          { month: 'Jan', cost: 12100 },
          { month: 'Feb', cost: 12680 },
          { month: 'Mar', cost: 13240.50 },
        ],
      },
      lastMonth: 12680.00,
      forecast: 13900.00,
      savingsOpportunity: 2180.00,
    }),
  
    // ==================== GLOBAL ANALYTICS ====================
    
    getAdvancedAnalytics: () => ({
      totalSpend: 41371.75,
      providers: {
        AWS: 12450.50,
        Azure: 15680.75,
        GCP: 13240.50,
      },
      trends: {
        mom: '+8.5%',
        yoy: '+32%',
      },
      topServices: [
        { service: 'Compute (All)', cost: 13900.00, percentage: 33.6 },
        { service: 'Databases (All)', cost: 9000.00, percentage: 21.7 },
        { service: 'Storage (All)', cost: 5850.00, percentage: 14.1 },
        { service: 'Networking', cost: 3420.00, percentage: 8.3 },
        { service: 'Serverless', cost: 3160.00, percentage: 7.6 },
        { service: 'Others', cost: 6041.75, percentage: 14.6 },
      ],
      anomalies: [
        {
          date: '2026-03-01',
          service: 'AWS Lambda',
          expected: 800,
          actual: 1450,
          deviation: '+81%',
          severity: 'High',
        },
        {
          date: '2026-02-28',
          service: 'Azure App Services',
          expected: 1200,
          actual: 1850,
          deviation: '+54%',
          severity: 'Medium',
        },
        {
          date: '2026-02-26',
          service: 'GCP Cloud Functions',
          expected: 900,
          actual: 1350,
          deviation: '+50%',
          severity: 'Medium',
        },
      ],
      costByRegion: [
        { region: 'US East', cost: 18500, percentage: 44.7 },
        { region: 'US West', cost: 12300, percentage: 29.7 },
        { region: 'Europe', cost: 7200, percentage: 17.4 },
        { region: 'Asia Pacific', cost: 3371.75, percentage: 8.1 },
      ],
      costByEnvironment: [
        { environment: 'Production', cost: 28960, percentage: 70 },
        { environment: 'Staging', cost: 8274, percentage: 20 },
        { environment: 'Development', cost: 4137, percentage: 10 },
      ],
    }),
  
    // ==================== MIGRATION ADVISOR ====================
    
    getMigrationRecommendations: () => [
      {
        id: 'mig-1',
        title: 'Migrate MySQL workloads to Aurora',
        description: 'Move 3 RDS MySQL instances to Aurora for better performance and cost savings',
        currentCost: 840.00,
        estimatedCost: 630.00,
        savings: 210.00,
        complexity: 'Medium',
        estimatedTime: '2-3 weeks',
        benefits: ['Better performance', 'Auto-scaling', 'Lower cost', 'Built-in HA'],
      },
      {
        id: 'mig-2',
        title: 'Move static assets to CloudFront + S3',
        description: 'Migrate static content from EC2 to S3 with CloudFront CDN',
        currentCost: 280.00,
        estimatedCost: 120.00,
        savings: 160.00,
        complexity: 'Low',
        estimatedTime: '1 week',
        benefits: ['Lower latency', 'Cost savings', 'Better scalability', 'Global edge network'],
      },
      {
        id: 'mig-3',
        title: 'Containerize monolithic applications',
        description: 'Migrate legacy applications to containers on ECS/EKS',
        currentCost: 1200.00,
        estimatedCost: 850.00,
        savings: 350.00,
        complexity: 'High',
        estimatedTime: '6-8 weeks',
        benefits: ['Better resource utilization', 'Easier deployment', 'Cost optimization', 'Scalability'],
      },
      {
        id: 'mig-4',
        title: 'Migrate on-premises data warehouse to Redshift',
        description: 'Move legacy data warehouse to AWS Redshift',
        currentCost: 3500.00,
        estimatedCost: 2100.00,
        savings: 1400.00,
        complexity: 'High',
        estimatedTime: '8-12 weeks',
        benefits: ['Managed service', 'Better performance', 'Cost savings', 'Easy scaling'],
      },
      {
        id: 'mig-5',
        title: 'Switch to Savings Plans',
        description: 'Commit to 1-year compute savings plans for steady workloads',
        currentCost: 2400.00,
        estimatedCost: 1680.00,
        savings: 720.00,
        complexity: 'Low',
        estimatedTime: '1 day',
        benefits: ['Immediate savings', 'Flexible usage', 'No upfront cost', 'Auto-applied'],
      },
    ],
  
    // ==================== CHANGE INVESTIGATION ====================
    
    getChangeEvents: () => [
      {
        id: 'chg-1',
        timestamp: '2026-03-03T06:45:00Z',
        provider: 'AWS',
        eventType: 'Configuration Change',
        resource: 'sg-1234abcd',
        resourceType: 'Security Group',
        changedBy: 'john.doe@company.com',
        action: 'Authorize Ingress',
        details: 'Added rule: Allow TCP 443 from 0.0.0.0/0',
        impact: 'Medium',
        region: 'us-east-1',
      },
      {
        id: 'chg-2',
        timestamp: '2026-03-03T05:30:00Z',
        provider: 'Azure',
        eventType: 'Resource Created',
        resource: 'vm-new-instance',
        resourceType: 'Virtual Machine',
        changedBy: 'jane.smith@company.com',
        action: 'Create VM',
        details: 'Created Standard_D4s_v3 instance in East US',
        impact: 'Low',
        region: 'eastus',
      },
      {
        id: 'chg-3',
        timestamp: '2026-03-03T04:15:00Z',
        provider: 'AWS',
        eventType: 'IAM Change',
        resource: 'role-admin-access',
        resourceType: 'IAM Role',
        changedBy: 'admin@company.com',
        action: 'Update Assume Role Policy',
        details: 'Modified trust relationship for role-admin-access',
        impact: 'High',
        region: 'global',
      },
      {
        id: 'chg-4',
        timestamp: '2026-03-03T03:00:00Z',
        provider: 'GCP',
        eventType: 'Configuration Change',
        resource: 'firewall-web-allow',
        resourceType: 'Firewall Rule',
        changedBy: 'ops@company.com',
        action: 'Update Firewall Rule',
        details: 'Modified source IP ranges for web-allow firewall rule',
        impact: 'Medium',
        region: 'global',
      },
      {
        id: 'chg-5',
        timestamp: '2026-03-03T02:20:00Z',
        provider: 'AWS',
        eventType: 'Resource Deleted',
        resource: 'i-5678efgh',
        resourceType: 'EC2 Instance',
        changedBy: 'automation@company.com',
        action: 'Terminate Instance',
        details: 'Terminated idle EC2 instance (unused for 30 days)',
        impact: 'Low',
        region: 'us-west-2',
      },
      {
        id: 'chg-6',
        timestamp: '2026-03-03T01:45:00Z',
        provider: 'Azure',
        eventType: 'Configuration Change',
        resource: 'prod-sql-db',
        resourceType: 'SQL Database',
        changedBy: 'dba@company.com',
        action: 'Scale Database',
        details: 'Scaled SQL database from S3 to S4 tier',
        impact: 'Medium',
        region: 'eastus',
      },
      {
        id: 'chg-7',
        timestamp: '2026-03-03T00:30:00Z',
        provider: 'AWS',
        eventType: 'Resource Created',
        resource: 'lambda-data-processor',
        resourceType: 'Lambda Function',
        changedBy: 'dev@company.com',
        action: 'Create Function',
        details: 'Deployed new Lambda function for data processing',
        impact: 'Low',
        region: 'us-east-1',
      },
      {
        id: 'chg-8',
        timestamp: '2026-03-02T23:15:00Z',
        provider: 'GCP',
        eventType: 'IAM Change',
        resource: 'service-account-prod',
        resourceType: 'Service Account',
        changedBy: 'security@company.com',
        action: 'Update IAM Policy',
        details: 'Added Cloud SQL Admin role to production service account',
        impact: 'High',
        region: 'global',
      },
    ],
  };