// ============================================
// MIGRATION ADVISOR - DEMO DATA SERVICE
// ============================================
// Generates realistic migration recommendations and TCO data

export const generateMigrationRecommendations = () => {
    return [
      {
        id: 'migration-rec-1',
        priority: 'high',
        type: 'cost_optimization',
        title: 'Migrate Production Database from AWS RDS to Azure SQL Database',
        currentSetup: {
          provider: 'aws',
          service: 'RDS PostgreSQL',
          instanceType: 'db.r5.xlarge',
          region: 'us-east-1',
          monthlyCost: 450,
          annualCost: 5400,
        },
        recommendedSetup: {
          provider: 'azure',
          service: 'Azure Database for PostgreSQL',
          instanceType: 'GP_Gen5_4',
          region: 'eastus',
          monthlyCost: 320,
          annualCost: 3840,
        },
        savings: {
          monthly: 130,
          annual: 1560,
          percentage: 28.9,
        },
        complexity: 'medium',
        estimatedEffort: '40 hours',
        estimatedDuration: '2-3 weeks',
        riskLevel: 'low',
        confidence: 92,
        benefits: [
          'Lower monthly costs by 29%',
          'Better integration with Azure Active Directory',
          'Improved backup options with long-term retention',
          'Better performance for read-heavy workloads',
        ],
        considerations: [
          'Requires application connection string updates',
          'Need to test compatibility with Azure PostgreSQL',
          'Plan maintenance window for migration',
          'Validate all database extensions are supported',
        ],
        prerequisites: [
          'Azure subscription with appropriate permissions',
          'Network connectivity between AWS and Azure',
          'Backup of current database',
          'Application code review for compatibility',
        ],
        migrationSteps: [
          {
            step: 1,
            phase: 'Assessment',
            title: 'Analyze current database',
            description: 'Document current database size, schema, extensions, and dependencies',
            estimatedTime: '4 hours',
            commands: [
              'psql -h mydb.aws.com -U admin -d production -c "\\l+"',
              'psql -h mydb.aws.com -U admin -d production -c "SELECT pg_size_pretty(pg_database_size(\'production\'));"',
            ],
          },
          {
            step: 2,
            phase: 'Planning',
            title: 'Create Azure Database for PostgreSQL',
            description: 'Provision Azure PostgreSQL instance with appropriate sizing',
            estimatedTime: '2 hours',
            commands: [
              'az postgres server create --resource-group myResourceGroup --name myazuredb --location eastus --admin-user myadmin --admin-password <password> --sku-name GP_Gen5_4 --version 14',
              'az postgres server firewall-rule create --resource-group myResourceGroup --server myazuredb --name AllowMyIP --start-ip-address <your-ip> --end-ip-address <your-ip>',
            ],
          },
          {
            step: 3,
            phase: 'Migration',
            title: 'Export data from AWS RDS',
            description: 'Create database dump from source',
            estimatedTime: '3 hours',
            commands: [
              'pg_dump -h mydb.aws.com -U admin -Fc production > production_backup.dump',
            ],
          },
          {
            step: 4,
            phase: 'Migration',
            title: 'Import data to Azure',
            description: 'Restore database to Azure PostgreSQL',
            estimatedTime: '4 hours',
            commands: [
              'pg_restore -h myazuredb.postgres.database.azure.com -U myadmin@myazuredb -d production -v production_backup.dump',
            ],
          },
          {
            step: 5,
            phase: 'Testing',
            title: 'Validate migration',
            description: 'Test application connectivity and run validation queries',
            estimatedTime: '8 hours',
            commands: [
              'psql -h myazuredb.postgres.database.azure.com -U myadmin@myazuredb -d production -c "SELECT COUNT(*) FROM users;"',
            ],
          },
          {
            step: 6,
            phase: 'Cutover',
            title: 'Update application',
            description: 'Update connection strings and deploy',
            estimatedTime: '4 hours',
            commands: [],
          },
        ],
      },
      {
        id: 'migration-rec-2',
        priority: 'medium',
        type: 'performance_improvement',
        title: 'Keep Compute Workloads in AWS, Optimize Instance Types',
        currentSetup: {
          provider: 'aws',
          service: 'EC2',
          instanceType: 't3.xlarge (10 instances)',
          region: 'us-east-1',
          monthlyCost: 1200,
          annualCost: 14400,
        },
        recommendedSetup: {
          provider: 'aws',
          service: 'EC2',
          instanceType: 'c6i.xlarge (10 instances)',
          region: 'us-east-1',
          monthlyCost: 1050,
          annualCost: 12600,
        },
        savings: {
          monthly: 150,
          annual: 1800,
          percentage: 12.5,
        },
        complexity: 'low',
        estimatedEffort: '16 hours',
        estimatedDuration: '1 week',
        riskLevel: 'low',
        confidence: 95,
        benefits: [
          'Cost reduction of 12.5%',
          'Better compute performance (20% faster)',
          'Lower latency for compute-intensive tasks',
          'Stay within AWS ecosystem (lower migration risk)',
        ],
        considerations: [
          'Need to test application on new instance type',
          'Minimal downtime required for instance swap',
        ],
        migrationSteps: [
          {
            step: 1,
            phase: 'Assessment',
            title: 'Analyze current workload',
            description: 'Review CPU and memory utilization patterns',
            estimatedTime: '2 hours',
          },
          {
            step: 2,
            phase: 'Testing',
            title: 'Launch test instances',
            description: 'Create c6i.xlarge instances and validate performance',
            estimatedTime: '4 hours',
          },
          {
            step: 3,
            phase: 'Migration',
            title: 'Rolling deployment',
            description: 'Replace instances one by one with new type',
            estimatedTime: '8 hours',
          },
        ],
      },
      {
        id: 'migration-rec-3',
        priority: 'high',
        type: 'cost_optimization',
        title: 'Migrate Object Storage from AWS S3 to GCP Cloud Storage',
        currentSetup: {
          provider: 'aws',
          service: 'S3',
          storageSize: '50 TB',
          region: 'us-east-1',
          monthlyCost: 1150,
          annualCost: 13800,
        },
        recommendedSetup: {
          provider: 'gcp',
          service: 'Cloud Storage',
          storageSize: '50 TB',
          region: 'us-central1',
          monthlyCost: 920,
          annualCost: 11040,
        },
        savings: {
          monthly: 230,
          annual: 2760,
          percentage: 20,
        },
        complexity: 'medium',
        estimatedEffort: '60 hours',
        estimatedDuration: '3-4 weeks',
        riskLevel: 'medium',
        confidence: 88,
        benefits: [
          'Save 20% on storage costs',
          'Better global CDN performance',
          'Faster downloads in APAC region',
          'Automatic data lifecycle management',
        ],
        considerations: [
          'Data transfer costs during migration',
          'Application code changes for GCP SDK',
          'Different pricing model (need to monitor)',
        ],
        prerequisites: [
          'GCP project with Storage permissions',
          'Network bandwidth for 50TB transfer',
          'Application compatibility review',
        ],
        migrationSteps: [
          {
            step: 1,
            phase: 'Assessment',
            title: 'Inventory S3 buckets',
            description: 'List all buckets and calculate total size',
            estimatedTime: '4 hours',
            commands: [
              'aws s3 ls',
              'aws s3 ls s3://my-bucket --recursive --summarize',
            ],
          },
          {
            step: 2,
            phase: 'Planning',
            title: 'Create GCP buckets',
            description: 'Set up Cloud Storage buckets with appropriate settings',
            estimatedTime: '4 hours',
            commands: [
              'gsutil mb -p my-project -c STANDARD -l us-central1 gs://my-gcp-bucket/',
              'gsutil versioning set on gs://my-gcp-bucket/',
            ],
          },
          {
            step: 3,
            phase: 'Migration',
            title: 'Transfer data using Storage Transfer Service',
            description: 'Use GCP Storage Transfer Service for bulk migration',
            estimatedTime: '40 hours (automated)',
            commands: [],
          },
          {
            step: 4,
            phase: 'Testing',
            title: 'Validate data integrity',
            description: 'Compare checksums and file counts',
            estimatedTime: '8 hours',
            commands: [
              'gsutil ls -r gs://my-gcp-bucket/ | wc -l',
            ],
          },
        ],
      },
      {
        id: 'migration-rec-4',
        priority: 'low',
        type: 'modernization',
        title: 'Migrate Legacy VMs to Serverless (AWS Lambda + Azure Functions)',
        currentSetup: {
          provider: 'aws',
          service: 'EC2',
          instanceType: 't3.medium (5 instances)',
          region: 'us-east-1',
          monthlyCost: 350,
          annualCost: 4200,
        },
        recommendedSetup: {
          provider: 'multi',
          service: 'Lambda + Azure Functions',
          instanceType: 'Serverless',
          region: 'multi-region',
          monthlyCost: 120,
          annualCost: 1440,
        },
        savings: {
          monthly: 230,
          annual: 2760,
          percentage: 65.7,
        },
        complexity: 'high',
        estimatedEffort: '120 hours',
        estimatedDuration: '8-12 weeks',
        riskLevel: 'medium',
        confidence: 75,
        benefits: [
          'Save 66% on compute costs',
          'Auto-scaling without management',
          'Pay only for actual usage',
          'Improved reliability with multi-cloud',
        ],
        considerations: [
          'Requires significant code refactoring',
          'Different programming model (event-driven)',
          'Cold start latency considerations',
          'Vendor lock-in across two platforms',
        ],
      },
    ];
  };
  
  export const generateTCOAnalysis = (userId: string) => {
    return {
      userId,
      generatedAt: new Date(),
      timeframe: '5-year',
      currentState: {
        totalAnnualCost: 87600,
        breakdown: {
          aws: {
            compute: 14400,
            database: 5400,
            storage: 13800,
            networking: 3600,
            other: 2400,
            total: 39600,
          },
          azure: {
            compute: 18000,
            database: 7200,
            storage: 8400,
            networking: 2400,
            other: 1800,
            total: 37800,
          },
          gcp: {
            compute: 6000,
            storage: 3000,
            ml: 1200,
            total: 10200,
          },
        },
        hidden_costs: {
          data_transfer: 4200,
          support: 6000,
          training: 3000,
          management_overhead: 12000,
          total: 25200,
        },
        total_with_hidden: 112800,
      },
      optimizedState: {
        totalAnnualCost: 62400,
        breakdown: {
          aws: {
            compute: 12600,
            database: 0,
            storage: 0,
            networking: 2400,
            other: 1800,
            total: 16800,
          },
          azure: {
            compute: 15000,
            database: 3840,
            storage: 6000,
            networking: 1800,
            other: 1200,
            total: 27840,
          },
          gcp: {
            compute: 4800,
            storage: 11040,
            ml: 1920,
            total: 17760,
          },
        },
        hidden_costs: {
          data_transfer: 3000,
          support: 4800,
          training: 1200,
          management_overhead: 8400,
          total: 17400,
        },
        total_with_hidden: 79800,
      },
      projections: {
        year1: {
          current: 112800,
          optimized: 79800,
          savings: 33000,
          migrationCost: 15000,
          netSavings: 18000,
        },
        year2: {
          current: 124080,
          optimized: 83790,
          savings: 40290,
          migrationCost: 0,
          netSavings: 40290,
        },
        year3: {
          current: 136488,
          optimized: 87980,
          savings: 48508,
          migrationCost: 0,
          netSavings: 48508,
        },
        year4: {
          current: 150137,
          optimized: 92378,
          savings: 57759,
          migrationCost: 0,
          netSavings: 57759,
        },
        year5: {
          current: 165150,
          optimized: 96997,
          savings: 68153,
          migrationCost: 0,
          netSavings: 68153,
        },
        totalSavings: 232710,
        roi: 1551,
        paybackPeriod: 0.45,
      },
      recommendations: [
        {
          action: 'Migrate databases to Azure',
          impact: 'High',
          savings: 1560,
          timeframe: 'Q1 2026',
        },
        {
          action: 'Move object storage to GCP',
          impact: 'High',
          savings: 2760,
          timeframe: 'Q2 2026',
        },
        {
          action: 'Optimize AWS EC2 instance types',
          impact: 'Medium',
          savings: 1800,
          timeframe: 'Q1 2026',
        },
        {
          action: 'Implement auto-scaling',
          impact: 'Medium',
          savings: 3600,
          timeframe: 'Q2 2026',
        },
      ],
    };
  };
  
  export const generateServiceComparison = () => {
    return [
      {
        category: 'Compute',
        workloadType: 'Web Applications',
        aws: {
          service: 'EC2',
          instanceType: 't3.xlarge',
          monthlyCost: 120,
          score: 85,
          pros: ['Wide instance variety', 'Mature ecosystem', 'Best global coverage'],
          cons: ['More expensive than competitors', 'Complex pricing'],
        },
        azure: {
          service: 'Virtual Machines',
          instanceType: 'B4ms',
          monthlyCost: 140,
          score: 80,
          pros: ['Hybrid cloud integration', 'Enterprise support', 'Windows licensing'],
          cons: ['Higher cost', 'Limited regions vs AWS'],
        },
        gcp: {
          service: 'Compute Engine',
          instanceType: 'n2-standard-4',
          monthlyCost: 110,
          score: 90,
          pros: ['Lowest cost', 'Sustained use discounts', 'Fast performance'],
          cons: ['Smaller ecosystem', 'Fewer regions'],
        },
        recommendation: 'gcp',
        reason: 'Best cost-performance ratio for standard web workloads',
      },
      {
        category: 'Database',
        workloadType: 'Relational Database (PostgreSQL)',
        aws: {
          service: 'RDS PostgreSQL',
          instanceType: 'db.r5.xlarge',
          monthlyCost: 450,
          score: 85,
          pros: ['Automated backups', 'Read replicas', 'Multi-AZ'],
          cons: ['Expensive', 'Limited customization'],
        },
        azure: {
          service: 'Azure Database for PostgreSQL',
          instanceType: 'GP_Gen5_4',
          monthlyCost: 320,
          score: 95,
          pros: ['Lower cost', 'Better AD integration', 'Hyperscale option'],
          cons: ['Fewer features than RDS'],
        },
        gcp: {
          service: 'Cloud SQL PostgreSQL',
          instanceType: 'db-n1-standard-4',
          monthlyCost: 380,
          score: 82,
          pros: ['Good performance', 'Easy scaling', 'IAM integration'],
          cons: ['Mid-range pricing', 'Limited regions'],
        },
        recommendation: 'azure',
        reason: 'Best pricing with enterprise features for managed PostgreSQL',
      },
      {
        category: 'Object Storage',
        workloadType: 'Large Media Files',
        aws: {
          service: 'S3',
          storageClass: 'Standard',
          costPerGB: 0.023,
          monthlyCost: 1150,
          score: 90,
          pros: ['Most mature', 'Best availability', 'Extensive integrations'],
          cons: ['Higher cost', 'Complex pricing tiers'],
        },
        azure: {
          service: 'Blob Storage',
          storageClass: 'Hot',
          costPerGB: 0.0208,
          monthlyCost: 1040,
          score: 85,
          pros: ['Good pricing', 'Enterprise features', 'Geo-redundancy'],
          cons: ['Slower than S3', 'Less ecosystem'],
        },
        gcp: {
          service: 'Cloud Storage',
          storageClass: 'Standard',
          costPerGB: 0.020,
          monthlyCost: 920,
          score: 95,
          pros: ['Lowest cost', 'Fast global CDN', 'Simple pricing'],
          cons: ['Smaller ecosystem', 'Fewer regions'],
        },
        recommendation: 'gcp',
        reason: 'Best pricing with excellent global performance for object storage',
      },
      {
        category: 'Container Orchestration',
        workloadType: 'Kubernetes',
        aws: {
          service: 'EKS',
          monthlyCost: 144,
          score: 88,
          pros: ['Deep AWS integration', 'Managed control plane', 'Fargate option'],
          cons: ['Control plane cost ($144/month)', 'Complex setup'],
        },
        azure: {
          service: 'AKS',
          monthlyCost: 0,
          score: 92,
          pros: ['Free control plane', 'Best Windows support', 'DevOps integration'],
          cons: ['Limited to Azure regions', 'Fewer features than EKS'],
        },
        gcp: {
          service: 'GKE',
          monthlyCost: 146,
          score: 95,
          pros: ['Created by k8s inventors', 'Best autopilot mode', 'Fast updates'],
          cons: ['Control plane cost', 'Smaller ecosystem'],
        },
        recommendation: 'azure',
        reason: 'Free control plane saves money, excellent for enterprise workloads',
      },
      {
        category: 'AI/ML',
        workloadType: 'Machine Learning Training',
        aws: {
          service: 'SageMaker + EC2 GPU',
          instanceType: 'p3.2xlarge',
          monthlyCost: 3060,
          score: 88,
          pros: ['Comprehensive ML platform', 'Wide model support', 'Good ecosystem'],
          cons: ['Expensive GPUs', 'Complex pricing'],
        },
        azure: {
          service: 'Azure Machine Learning',
          instanceType: 'NC6s_v3',
          monthlyCost: 2700,
          score: 85,
          pros: ['Good pricing', 'Studio interface', 'MLOps features'],
          cons: ['Less mature than AWS', 'Fewer pre-trained models'],
        },
        gcp: {
          service: 'Vertex AI + Compute Engine GPU',
          instanceType: 'n1-standard-8 + T4',
          monthlyCost: 1890,
          score: 95,
          pros: ['Lowest GPU cost', 'TPU access', 'TensorFlow integration'],
          cons: ['Smaller ecosystem', 'Fewer regions with GPUs'],
        },
        recommendation: 'gcp',
        reason: 'Best GPU pricing and TPU access make it ideal for ML workloads',
      },
    ];
  };
  
  export const generateCostBreakdown = (cloudAccountId: string) => {
    return {
      cloudAccountId,
      period: 'last_30_days',
      totalCost: 3289,
      breakdown: {
        compute: {
          cost: 1200,
          percentage: 36.5,
          services: [
            { name: 'EC2 instances', cost: 850, instances: 10 },
            { name: 'Lambda', cost: 180, invocations: 2500000 },
            { name: 'ECS', cost: 170, tasks: 15 },
          ],
        },
        database: {
          cost: 450,
          percentage: 13.7,
          services: [
            { name: 'RDS PostgreSQL', cost: 380, instances: 2 },
            { name: 'DynamoDB', cost: 70, tables: 8 },
          ],
        },
        storage: {
          cost: 1150,
          percentage: 35.0,
          services: [
            { name: 'S3', cost: 950, sizeGB: 45000 },
            { name: 'EBS volumes', cost: 200, sizeGB: 2000 },
          ],
        },
        networking: {
          cost: 300,
          percentage: 9.1,
          services: [
            { name: 'Data transfer OUT', cost: 180, sizeGB: 9000 },
            { name: 'Load Balancers', cost: 80, count: 3 },
            { name: 'VPN', cost: 40, connections: 2 },
          ],
        },
        other: {
          cost: 189,
          percentage: 5.7,
          services: [
            { name: 'CloudWatch', cost: 45 },
            { name: 'Config', cost: 38 },
            { name: 'CloudTrail', cost: 36 },
            { name: 'Security Hub', cost: 35 },
            { name: 'Inspector', cost: 35 },
          ],
        },
      },
      migrationOpportunities: [
        {
          service: 'S3 Storage',
          currentCost: 950,
          targetProvider: 'GCP Cloud Storage',
          projectedCost: 760,
          monthlySavings: 190,
          annualSavings: 2280,
        },
        {
          service: 'RDS PostgreSQL',
          currentCost: 380,
          targetProvider: 'Azure Database',
          projectedCost: 270,
          monthlySavings: 110,
          annualSavings: 1320,
        },
      ],
    };
  };